import { StyleSheet } from 'react-native';

export const colors = {
  ink: '#f7f8fa',
  muted: '#aab3c0',
  dim: '#7d8796',
  canvas: '#0b0d12',
  surface: '#151a23',
  surfaceRaised: '#1c2430',
  line: '#2a3442',
  primary: '#8ce6bd',
  primaryInk: '#07150f',
  warning: '#f4c95d',
  danger: '#f08a87',
  dangerSurface: '#3a2024',
  blue: '#9bc9ff',
};

export const common = StyleSheet.create({
  flex: { flex: 1 },
  screen: { flex: 1, backgroundColor: colors.canvas },
  content: { paddingHorizontal: 18, paddingBottom: 32 },
  title: { color: colors.ink, fontSize: 30, fontWeight: '800', letterSpacing: -0.4 },
  subtitle: { color: colors.muted, fontSize: 15, lineHeight: 21, marginTop: 6 },
  sectionTitle: { color: colors.ink, fontSize: 18, fontWeight: '800', marginBottom: 10 },
  label: { color: colors.muted, fontSize: 13, fontWeight: '700', marginBottom: 7 },
  input: {
    backgroundColor: colors.surface,
    borderColor: colors.line,
    borderRadius: 12,
    borderWidth: 1,
    color: colors.ink,
    fontSize: 16,
    minHeight: 48,
    paddingHorizontal: 14,
    paddingVertical: 11,
  },
  card: {
    backgroundColor: colors.surface,
    borderColor: colors.line,
    borderRadius: 16,
    borderWidth: 1,
    padding: 15,
  },
  button: {
    alignItems: 'center',
    borderRadius: 13,
    minHeight: 48,
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  buttonText: { fontSize: 15, fontWeight: '800' },
  row: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.line,
    borderRadius: 15,
    borderWidth: 1,
    flexDirection: 'row',
    marginBottom: 10,
    minHeight: 76,
    padding: 13,
  },
  rowTitle: { color: colors.ink, fontSize: 16, fontWeight: '800' },
  rowSub: { color: colors.muted, fontSize: 13, lineHeight: 18, marginTop: 3 },
  note: { color: colors.dim, fontSize: 13, lineHeight: 19 },
  divider: { backgroundColor: colors.line, height: StyleSheet.hairlineWidth, marginVertical: 18 },
});
